services:
  db:
    image: postgres:14
    container_name: rlink-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rlink-web
    restart: always
    env_file:
      - .env
    ports:
      - "9292:9292"
    depends_on:
      db:
        condition: service_healthy

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rlink-bot
    restart: always
    command: ["bundle", "exec", "ruby", "main.rb"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: