development:
  adapter: postgres
  host:     db
  database: ruby_url_shortener_development
  user:     <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

test:
  adapter: postgres
  host:     db
  database: ruby_url_shortener_test
  user:     <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>

production:
  adapter: postgres
  host:     db
  database: ruby_url_shortener_production
  user:     <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>